services:
  ultimate-rvc:
    build:
      context: .
    ports:
      - "7860:7860"
    volumes:
      - urvc-data:/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  urvc-data:
